version: '2'
services:
  db:
    ports:
      - '5432:5432'
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: 'una_healt_user'
      POSTGRES_PASSWORD: 'una_healt_pass'
      POSTGRES_DB: 'una_healt_db'
  web:
    mem_limit: '1012m'
    mem_reservation: '512M'
    container_name: "backend_una_health"
    build: .
    command: python manage.py runserver 0.0.0.0:8100
    volumes:
      - .:/code
    ports:
      - "8100:8100"
    depends_on:
      - db

volumes:
  postgres_data: