# Generated by Django 3.2.25 on 2024-06-04 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Glucose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=100)),
                ('device_timestamp', models.DateTimeField()),
                ('record_type', models.IntegerField(default=0)),
                ('glucose_history', models.DecimalField(decimal_places=2, max_digits=5)),
                ('glucose_scan', models.DecimalField(decimal_places=2, max_digits=5)),
                ('non_numeric_rapid_acting_insulin', models.CharField(max_length=500, null=True)),
                ('rapid_acting_insulin', models.IntegerField(default=0)),
                ('non_numeric', models.CharField(max_length=500)),
                ('food_data', models.CharField(max_length=500)),
                ('carbohydrates_grams', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carbohydrates_servings', models.DecimalField(decimal_places=2, max_digits=5)),
                ('non_numeric_depot_insulin', models.CharField(max_length=500)),
                ('depot_insulin', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('glucose_test_strip', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ketone', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mealtime_insulin', models.IntegerField(default=0)),
                ('correction_insulin', models.IntegerField(default=0)),
                ('user_insulin_change', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
